##
# @author George Sofianos
# @author Aris Katsanas
# This docker compose file is for having an XMLCONV demo stack on rancher. 
# Please change the passwords before running it through rancher-compose.
##

## TOMCAT SERVER
tomcat:  
  image: eeacms/xmlconv:latest
  env_file: docker.env
  links:
    - mysql
    - basex
  volumes_from:
    - data-xmlconv
  labels:
    io.rancher.container.pull_image: always
    io.rancher.sidekicks: data-xmlconv, scpserver, basex

scpserver:
  image: eeacms/scp-server
  ports:
  - 2222:22
  environment:
    AUTHORIZED_KEYS:
    #  Add your key here
    #  ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAteQ38qb7....uC839w== authorized key
    DATADIR: /opt/
    USERID: 0
    GROUPID: 0
  volumes_from:
  - data-xmlconv

## DATABASE CONTAINERS
mysql:
  image: mysql:5.5
  ports:
    - "31306:3306"
  environment: 
    MYSQL_ROOT_PASSWORD: xxxxx
  volumes_from:
    - data-mysql
  labels:
    io.rancher.sidekicks: data-mysql
    io.rancher.container.pull_image: always

## XQUERY CONTAINERS
basex:
  image: dev4ka/docker-basex
  ports:
    - "31984:1984"
  environment:
    BASEX_JVM: -Xmx4096m -Xss4m
  volumes:
    - /opt/xmlconv/queries:/srv/BaseXModule

## DATA CONTAINERS
data-mysql:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
    - /data/xmlconv/mysql:/var/lib/mysql

data-xmlconv:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
    - /opt/xmlconv:/opt/xmlconv
