version: '2'
services:
  xmlconv-rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5673:5672'
      - '15673:15672'
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: qawsedrf
      RABBITMQ_NODENAME: xmlconv-rabbitmq